#!/bin/sh

if [ ! -d stupidgit_gui ]
then
    echo "You must run buildapp from stupidgit root directory!"
    exit 1
fi

if [ -d dist ]
then
    rm -rf dist/StupidGit.app
else
    mkdir dist
fi

# Create app directories
appdir=dist/StupidGit.app/Contents/
bindir=$appdir/MacOS
resource_dir=$appdir/Resources

mkdir -p $bindir
mkdir -p $resource_dir/lib

# Copy core files
cp setup/osx/Info.plist setup/osx/PkgInfo $appdir/
cp setup/osx/StupidGit $bindir/
cp setup/osx/StupidGit-askpass $bindir/StupidGit-askpass
ln -s /System/Library/Frameworks/Python.framework/Versions/2.5/Resources/Python.app/Contents/MacOS/Python $bindir/
cp -r stupidgit_gui $resource_dir/lib/stupidgit_gui
rm -f $resource_dir/lib/stupidgit_gui/*.pyc

# Copy resources
cp icon/icon.icns $resource_dir/
resources="commit.png discard.png fetch.png push.png refresh.png switch.png stupidgit.xrc"
for res in $resources
do
    cp resources/$res $resource_dir/
done
